

GET http://localhost:8000/source?query=any HTTP/1.1

###

POST http://localhost:8000/source HTTP/1.1
d

{
    "type": "pulse",
    "name": "Example Source",
    "desc": "Example pulse source for testing"
}
