[project]
name = "registry-api"
version = "0.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "briefcase>=0.4.1",
    "jsonschema>=4.26.0",
    "python-sqlite-log-handler>=1.1.0",
    "quart>=0.20.0",
]



# content below this line added by briefcase convert
# This project was generated with 0.4.1 using template: https://github.com/beeware/briefcase-template @ v0.4.1
[tool.briefcase]
project_name = "Registry Api"
bundle = "com.signalregistry.registry-api"
version = "0.4.0"
url = "https://example.com/registry-api"
license.file = "LICENSE"
author = "Hüseyin YİĞİT"
author_email = "yigit.hsyn@gmail.com"

[tool.briefcase.app.registry-api]
formal_name = "Registry Api"
description = "Add your description here"
long_description = """More details about the app should go here.
"""
sources = [
    "src/registry_api",
]
test_sources = [
    "tests",
]
console_app = true

requires = [
    # Add your cross-platform app requirements here
]
test_requires = [
    # Add your cross-platform test requirements here
]

[tool.briefcase.app.registry-api.macOS]
universal_build = true
requires = [
    # Add your macOS-specific app requirements here
]

[tool.briefcase.app.registry-api.linux]
requires = [
    # Add your Linux-specific app requirements here
]

[tool.briefcase.app.registry-api.linux.system.debian]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.registry-api.linux.system.rhel]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.registry-api.linux.system.suse]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.registry-api.linux.system.arch]
system_requires = [
    # Add any system packages needed at build the app here
]

system_runtime_requires = [
    # Add any system packages needed at runtime here
]

[tool.briefcase.app.registry-api.linux.flatpak]
flatpak_runtime = "org.freedesktop.Platform"
flatpak_runtime_version = "25.08"
flatpak_sdk = "org.freedesktop.Sdk"

[tool.briefcase.app.registry-api.windows]
requires = [
    # Add your Windows-specific app requirements here
]

# Mobile deployments
[tool.briefcase.app.registry-api.iOS]
requires = [
    # Add your iOS-specific app requirements here
]

[tool.briefcase.app.registry-api.android]
requires = [
    # Add your Android-specific app requirements here
]

# Web deployments
[tool.briefcase.app.registry-api.web]
requires = [
    # Add your web-specific app requirements here
]

